<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-ctype/bootstrap.php';
require_once __DIR__ . '/paragonie/random_compat/lib/random.php';
